# Generated by Django 6.0.5 on 2026-05-14 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Код ячейки",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ячейка склада",
                "verbose_name_plural": "Ячейки склада",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="Количество (+ приход / − расход)",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Приход"),
                            ("issue", "Расход"),
                            ("transfer_out", "Перемещение (отправка)"),
                            ("transfer_in", "Перемещение (приём)"),
                            ("reserve", "Резерв"),
                            ("reserve_release", "Снятие резерва"),
                            ("writeoff", "Списание"),
                            ("inventory", "Инвентаризация"),
                        ],
                        max_length=32,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Комментарий"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "reference_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="warehouse.storagelocation",
                        verbose_name="Ячейка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение склада",
                "verbose_name_plural": "Движения склада",
                "ordering": ["-created_at"],
            },
        ),
    ]
