# Generated by Django 6.0.5 on 2026-05-15 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_purchaserequisitionline_quantity_received"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="purchase_requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="procurement.purchaserequisition",
                verbose_name="Заявка на закупку",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="requisition_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="procurement.purchaserequisitionline",
                verbose_name="Строка заявки",
            ),
        ),
    ]
