# Generated by Django 6.0.5 on 2026-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Имя / контактное лицо"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Организация"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                ("requisites", models.TextField(blank=True, verbose_name="Реквизиты")),
                (
                    "manager_notes",
                    models.TextField(blank=True, verbose_name="Комментарии менеджера"),
                ),
                (
                    "preferences",
                    models.TextField(blank=True, verbose_name="Предпочтения клиента"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Не указан"),
                            ("pending", "Ожидает оплаты"),
                            ("partial", "Частично оплачен"),
                            ("paid", "Оплачен"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["organization", "name"],
            },
        ),
    ]
