# Generated by Django 6.0.5 on 2026-05-14 14:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Код (SKU)",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "шт."),
                            ("m", "м"),
                            ("m2", "м²"),
                            ("m3", "м³"),
                            ("kg", "кг"),
                            ("sheet", "лист"),
                            ("set", "комплект"),
                        ],
                        default="pcs",
                        max_length=16,
                        verbose_name="Ед. изм.",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Минимальный остаток",
                    ),
                ),
                (
                    "storage_hint",
                    models.CharField(
                        blank=True,
                        help_text="Позже можно связать с ячейкой склада через движения.",
                        max_length=255,
                        verbose_name="Подсказка по размещению (текст)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=64, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Шаблон изделия",
                "verbose_name_plural": "Шаблоны изделий",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BillOfMaterialLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Кол-во на 1 изделие",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_usages",
                        to="catalog.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="catalog.producttemplate",
                        verbose_name="Изделие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка спецификации",
                "verbose_name_plural": "Спецификации (BOM)",
                "unique_together": {("product", "material")},
            },
        ),
    ]
