# Generated by Django 6.0.5 on 2026-05-15 15:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="quantity_received",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Уже принято на склад",
            ),
        ),
    ]
